name: Unit test for shared modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  androidUnitTest:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/java/openjdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests shared modules
        run: ./gradlew test

  iosUnitTest:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/java/openjdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: xcodebuild test -project iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 7' -derivedDataPath build ONLY_ACTIVE_ARCH=YES


