name: Build and Test KMM Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/java/openjdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android and shared modules
        run: ./gradlew build

      - name: Run unit tests for Android and shared modules
        run: ./gradlew test

  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --project-directory=iosApp
          pod init

      - name: Build iOS framework
        run: ./gradlew :shared:build

      - name: Run iOS unit tests
        run: ./gradlew :shared:iosTest
