name: Tests

on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string

jobs:
  Android:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunAndroid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew clean testDebug -p androidApp/

  iOS:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - run: xcodebuild build test -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: "/Users/runner/Library/Developer/Xcode/DerivedData/*"

  KMP-Common-Module:
    if: ${{ inputs.shouldRunKmp == 'true'}}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew clean testDebugUnitTest -p shared/

  KMP-iOS:
    if: ${{ inputs.shouldRunKmp == 'true'}}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Test without Building iOS Application
        run:  xcodebuild "build" "-project" "./iosApp/iosApp.xcodeproj" "-scheme" "iosApp" "-configuration" "Release" "-destination" "platform=iOS Simulator,name=iPhone 15,OS=17.5" test